export type DataItem = {
  id: string;
  name: string;
  location: string;
  experience: string;
  rating: number;
  specialties: string[];
  paymentRate: string;
  desc: string;
};

export const PENJAHIT_DATA: DataItem[] = [
  {
    id: "1",
    name: "Budi Tailor",
    location: "Jl. Tukad Badung No. 128, Denpasar, Bali",
    experience: "10 Tahun",
    rating: 4.8,
    specialties: ["Jas", "Kebaya", "Setelan Formal", "Profesional", "Custom"],
    paymentRate: "100rb-150rb",
    desc: "Budi Tailor adalah penjahit profesional dengan pengalaman lebih dari 10 tahun dalam menjahit berbagai jenis pakaian formal dan custom. Melayani kebutuhan jahitan personal maupun pemesanan dalam jumlah besar, dengan kualitas jahitan rapi dan presisi. Cocok untuk kamu yang mencari setelan jas atau kebaya dengan detail yang menonjol.",
  },
  {
    id: "2",
    name: "Sari Jahit",
    location: "Jl. Nangka Selatan No. 45, Denpasar, Bali",
    experience: "8 Tahun",
    rating: 4.6,
    specialties: ["Kebaya", "Gaun", "Baju Pesta", "Wanita", "Custom"],
    paymentRate: "80rb-130rb",
    desc: "Sari Jahit dikenal sebagai spesialis dalam pembuatan kebaya dan gaun pesta wanita. Dengan pengalaman 8 tahun, ia mampu menghasilkan desain yang anggun dan elegan sesuai permintaan pelanggan. Pelayanan ramah dan pengerjaan yang tepat waktu menjadikan Sari Jahit pilihan tepat untuk momen spesial kamu.",
  },
  {
    id: "3",
    name: "Made Tailor",
    location: "Jl. Gunung Salak No. 23, Denpasar, Bali",
    experience: "12 Tahun",
    rating: 4.9,
    specialties: ["Jas", "Kemeja", "Celana", "Pria", "Formal"],
    paymentRate: "120rb-170rb",
    desc: "Made Tailor adalah penjahit berpengalaman selama lebih dari 12 tahun yang ahli dalam menjahit pakaian pria seperti jas, kemeja, dan celana formal. Mengutamakan kepuasan pelanggan, Made Tailor selalu memastikan setiap detail dijahit dengan rapi dan hasil akhir yang pas di badan.",
  },
  {
    id: "4",
    name: "Dewi Fashion",
    location: "Jl. Diponegoro No. 56, Denpasar, Bali",
    experience: "7 Tahun",
    rating: 4.7,
    specialties: ["Gaun", "Dress", "Kebaya", "Remaja", "Pesta"],
    paymentRate: "90rb-140rb",
    desc: "Dewi Fashion melayani berbagai jenis jahitan wanita, khususnya dress dan kebaya. Dengan 7 tahun pengalaman, penjahit ini mengerti kebutuhan remaja hingga dewasa yang ingin tampil elegan dalam acara pesta atau formal. Gaya modern dipadukan dengan teknik jahitan yang terampil.",
  },
  {
    id: "5",
    name: "Yuda Tailor",
    location: "Jl. Teuku Umar No. 88, Denpasar, Bali",
    experience: "15 Tahun",
    rating: 4.8,
    specialties: ["Seragam", "Kemeja", "Celana", "Kantor", "Formal"],
    paymentRate: "100rb-160rb",
    desc: "Yuda Tailor adalah solusi ideal untuk kamu yang membutuhkan pakaian kantor, seragam, atau setelan formal lainnya. Berpengalaman selama 15 tahun, Yuda Tailor dikenal karena hasil jahitannya yang rapi, awet, dan nyaman dipakai sehari-hari.",
  },
  {
    id: "6",
    name: "Komang Style",
    location: "Jl. Hayam Wuruk No. 9, Denpasar, Bali",
    experience: "5 Tahun",
    rating: 4.5,
    specialties: ["Jas", "Vest", "Kostum", "Pria", "Custom"],
    paymentRate: "90rb-120rb",
    desc: "Komang Style menggabungkan ketepatan waktu dan kualitas presisi dalam setiap jahitannya. Cocok untuk kamu yang mencari jas, vest, atau kostum pria yang unik dan bisa disesuaikan dengan kebutuhan acara. Dengan 5 tahun pengalaman, Komang siap membantu tampil beda.",
  },
  {
    id: "7",
    name: "Lia Jahit",
    location: "Jl. Letda Made Putra No. 32, Denpasar, Bali",
    experience: "9 Tahun",
    rating: 4.6,
    specialties: ["Kebaya", "Dress", "Casual", "Wanita", "Custom"],
    paymentRate: "80rb-110rb",
    desc: "Lia Jahit berfokus pada jahitan wanita seperti kebaya, dress casual, hingga pakaian pesta. Dengan pengalaman hampir satu dekade, Lia dikenal akan kreativitas desain dan hasil jahitan yang memanjakan pelanggan. Setiap pakaian dibuat dengan perhatian tinggi pada detail.",
  },
  {
    id: "8",
    name: "Ari Tailor",
    location: "Jl. Cargo Permai No. 17, Denpasar, Bali",
    experience: "11 Tahun",
    rating: 4.7,
    specialties: ["Jas", "Kemeja", "Pakaian Kantor", "Seragam", "Custom"],
    paymentRate: "110rb-150rb",
    desc: "Ari Tailor adalah penjahit andalan untuk kebutuhan jas dan pakaian kerja. Dengan pengalaman lebih dari 10 tahun, Ari mampu melayani pesanan skala individu maupun perusahaan. Kualitas dan konsistensi menjadi nilai utama dalam setiap proyeknya.",
  },
  {
    id: "9",
    name: "Putri Tailor",
    location: "Jl. Gatot Subroto Barat No. 14, Denpasar, Bali",
    experience: "6 Tahun",
    rating: 4.4,
    specialties: ["Kebaya", "Gaun", "Dress", "Pesta", "Wanita"],
    paymentRate: "85rb-120rb",
    desc: "Putri Tailor adalah pilihan ideal bagi wanita yang ingin tampil memukau dalam acara formal maupun pesta. Spesialisasinya dalam dress dan kebaya dipadukan dengan sentuhan modern dan klasik yang elegan. Jahitan rapi dan nyaman dipakai seharian.",
  },
  {
    id: "10",
    name: "Bagus Tailor",
    location: "Jl. Imam Bonjol No. 100, Denpasar, Bali",
    experience: "10 Tahun",
    rating: 4.7,
    specialties: ["Setelan", "Kemeja", "Celana", "Formal", "Pria"],
    paymentRate: "100rb-140rb",
    desc: "Bagus Tailor telah menjahit berbagai jenis pakaian pria, mulai dari setelan, kemeja, hingga celana formal. Dengan pengalaman selama satu dekade, ia selalu mengutamakan kenyamanan dan kualitas bahan dalam setiap hasil jahitan.",
  },
  {
    id: "11",
    name: "Wayan Tailor",
    location: "Jl. Mahendradatta No. 22, Denpasar, Bali",
    experience: "13 Tahun",
    rating: 4.9,
    specialties: ["Jas", "Seragam", "Formal", "Custom", "Kemeja"],
    paymentRate: "110rb-160rb",
    desc: "Wayan Tailor adalah penjahit profesional yang telah berpengalaman selama 13 tahun. Mengutamakan ketelitian dalam setiap jahitan, Wayan menjadi langganan pelanggan korporat dan perorangan untuk pembuatan jas dan seragam kerja. Ia juga melayani permintaan desain khusus sesuai kebutuhan pelanggan.",
  },
  {
    id: "12",
    name: "Tari Jahit",
    location: "Jl. Antasura No. 50, Denpasar, Bali",
    experience: "6 Tahun",
    rating: 4.5,
    specialties: ["Dress", "Casual", "Kebaya", "Remaja", "Custom"],
    paymentRate: "75rb-100rb",
    desc: "Tari Jahit fokus pada kebutuhan fesyen wanita modern dan remaja. Dengan sentuhan kreatif dan pengalaman selama 6 tahun, Tari mampu menghadirkan dress yang nyaman dipakai sehari-hari hingga kebaya yang anggun untuk acara khusus. Cocok untuk kamu yang ingin tampil stylish dengan desain custom.",
  },
  {
    id: "13",
    name: "Adi Tailor",
    location: "Jl. WR Supratman No. 70, Denpasar, Bali",
    experience: "8 Tahun",
    rating: 4.6,
    specialties: ["Jas", "Pakaian Kantor", "Celana", "Formal", "Custom"],
    paymentRate: "100rb-140rb",
    desc: "Adi Tailor adalah spesialis pakaian pria dengan pengalaman selama 8 tahun. Ia menangani jas, celana, hingga seragam kantor dengan kualitas tinggi dan ketepatan ukuran. Pelayanan yang profesional membuat banyak pelanggan tetap mempercayakan kebutuhan jahitannya kepada Adi.",
  },
  {
    id: "14",
    name: "Nia Jahit",
    location: "Jl. Sutoyo No. 33, Denpasar, Bali",
    experience: "7 Tahun",
    rating: 4.7,
    specialties: ["Gaun", "Dress", "Pesta", "Kebaya", "Wanita"],
    paymentRate: "85rb-120rb",
    desc: "Nia Jahit melayani pembuatan dress dan kebaya untuk acara-acara penting. Dikenal dengan jahitan rapi dan desain feminin, Nia sangat cocok untuk kamu yang ingin tampil memukau di acara formal. Pengalaman 7 tahun membentuk keahlian dan selera desain yang memuaskan pelanggan.",
  },
  {
    id: "15",
    name: "Gede Tailor",
    location: "Jl. Tegal Wangi No. 17, Denpasar, Bali",
    experience: "10 Tahun",
    rating: 4.8,
    specialties: ["Jas", "Seragam", "Formal", "Kantor", "Custom"],
    paymentRate: "100rb-150rb",
    desc: "Gede Tailor adalah penjahit terpercaya untuk kebutuhan korporat dan pakaian formal lainnya. Dengan hasil jahitan yang kuat dan tahan lama, Gede sering menjadi pilihan untuk pemesanan seragam dalam jumlah banyak. Cocok untuk institusi dan individu yang mengutamakan kualitas.",
  },
  {
    id: "16",
    name: "Putu Tailor",
    location: "Jl. Pulau Kawe No. 20, Denpasar, Bali",
    experience: "9 Tahun",
    rating: 4.6,
    specialties: ["Jas", "Vest", "Pria", "Kemeja", "Custom"],
    paymentRate: "90rb-130rb",
    desc: "Putu Tailor menawarkan jasa jahit khusus untuk pakaian pria, mulai dari vest, kemeja, hingga jas. Mengutamakan kenyamanan bahan dan keakuratan ukuran, Putu memastikan setiap pakaian terasa pas dan terlihat profesional. Sudah dipercaya selama 9 tahun oleh berbagai kalangan.",
  },
  {
    id: "17",
    name: "Ayu Jahit",
    location: "Jl. Diponegoro No. 88, Denpasar, Bali",
    experience: "6 Tahun",
    rating: 4.4,
    specialties: ["Dress", "Kebaya", "Wanita", "Custom", "Pesta"],
    paymentRate: "80rb-110rb",
    desc: "Ayu Jahit menghadirkan gaya feminin dan elegan melalui koleksi kebaya dan dress buatannya. Ia terkenal akan sentuhan personal pada setiap desain dan pengerjaan detail yang sangat diperhatikan. Pelanggan puas dengan hasil akhir yang sesuai ekspektasi untuk acara penting.",
  },
  {
    id: "18",
    name: "Yoga Tailor",
    location: "Jl. Gunung Agung No. 55, Denpasar, Bali",
    experience: "11 Tahun",
    rating: 4.7,
    specialties: ["Setelan", "Kemeja", "Seragam", "Formal", "Custom"],
    paymentRate: "100rb-140rb",
    desc: "Yoga Tailor adalah pilihan utama untuk kamu yang ingin tampil rapi dalam balutan setelan formal. Dengan pengalaman lebih dari 11 tahun, Yoga mengedepankan kenyamanan dan profesionalisme dalam setiap hasil jahitannya. Ideal untuk individu maupun kantor yang butuh jahitan skala banyak.",
  },
  {
    id: "19",
    name: "Tini Fashion",
    location: "Jl. Pulau Moyo No. 10, Denpasar, Bali",
    experience: "5 Tahun",
    rating: 4.5,
    specialties: ["Gaun", "Dress", "Kebaya", "Remaja", "Wanita"],
    paymentRate: "70rb-100rb",
    desc: "Tini Fashion melayani kebutuhan fesyen wanita muda dengan harga terjangkau dan desain yang selalu mengikuti tren. Dari gaun santai hingga kebaya pesta, Tini memberikan hasil jahitan yang nyaman dan pas sesuai dengan selera pelanggan muda.",
  },
  {
    id: "20",
    name: "Ardi Tailor",
    location: "Jl. Merdeka No. 21, Denpasar, Bali",
    experience: "12 Tahun",
    rating: 4.8,
    specialties: ["Jas", "Kemeja", "Pakaian Kantor", "Formal", "Custom"],
    paymentRate: "100rb-150rb",
    desc: "Ardi Tailor dikenal dengan jahitannya yang presisi dan finishing yang rapi. Spesialis dalam jas dan pakaian kerja, Ardi menjadi andalan bagi para profesional yang ingin tampil prima. Pelayanan personal dan pengerjaan cepat menjadi nilai tambah dari Ardi.",
  },
];
